services:
  vite:
    build:
      context: .
      target: dev     # 👈 podés cambiarlo a "production" si querés build final
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
